### ISSUE TITLE
Bug: Extractor: HTTP 400 when generating groups template on a consumption tier APIM

### ISSUE THREAD

**Issue by sh-jthorpe** [Azure/azure-api-management-devops-resource-kit#849]
### Report

Extractor is trying to generate a groups template on a consumption tier APIM service.

When it attempts to do so, it's getting a HTTP 400 error:

```
[23:09:26 INF] Started generation of groups template...
[23:09:28 ERR] Error occured: Response status code does not indicate success: 400 (Bad Request).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
```

### Expected Behavior

It either shouldn't generate a groups template on a consumption tier APIM service, or it should generate a groups template without error.

### Actual Behavior

Extractor fails with error

### Steps to Reproduce the Problem

1. Using consumption tier APIM service
2. Run extractor using below config

```json
{
  "sourceApimName": "shd-DataGateway-apim1",
  "resourceGroup": "shd-DataGateway-rg",
  "fileFolder": "Deployments/Apim",
  "paramServiceUrl": "true",
  "splitApis": "false",
  "paramNamedValuesKeyVaultSecrets": "true",
  "paramNamedValue": "true",
  "paramApiLoggerId": "true",
  "paramLogResourceId": "true",
  "paramBackend": "true"
}
```

Plus some options are passed in the command line.

```shell
"--extractorConfig $BasePath\ExtractorConfig.json", 
    "--linkedTemplatesSasToken '$StorageBlobSasKey'", 
    "--policyXMLSasToken '$StorageBlobSasKey'", 
    "--linkedTemplatesBaseUrl $StorageBlobUrl/apim/template/", 
    "--policyXMLBaseUrl $StorageBlobUrl/apim/template/policies/", 
    "--destinationApimName $ApimServiceName")
```

### Component

Extractor

### DevOps Resource Kit Version

1.0.0

### .NET Version

.NET 6.0.12

### OS

AZ Devops windows-2019 runner

### API Management Configuration

- Consumption tier
- No products
- Many APIs
- I have full admin access

### Logs

```shell
[23:08:41 INF] Booting up Azure-Api-Management-DevOps-Resource-Kit v1.0.0.0 running .NET .NET 6.0.12
[23:08:41 INF] Recognized extract command...
[23:08:42 INF] API Management Template
[23:08:42 INF] Connecting to shd-DataGateway-apim1 API Management Service on shd-DataGateway-rg Resource Group ...
[23:08:42 INF] No specific parameters are set for template generation...
[23:08:42 INF] There were no `singleApiName` or `multipleApiNames` specified. Loading all API names from SourceApimName directly...
[23:08:45 INF] Started generation of api template...
[23:08:45 INF] 6 APIs found ...
[23:08:53 WRN] No diagnostics found for api contacts;rev=1
[23:08:56 WRN] Policy for api contacts;rev=1 not found
[23:08:56 INF] contacts;rev=1 Product API found ...
[23:08:56 INF] Extracting products from contacts;rev=1 API:
[23:09:01 WRN] No tags found for api contacts;rev=1
[23:09:04 WRN] No tags found for api 'contacts;rev=1' and operation create-invitation
[23:09:04 WRN] No tags found for api 'contacts;rev=1' and operation find-dataverse-contact
[23:09:04 WRN] No tags found for api 'contacts;rev=1' and operation upsert-contact
[23:09:04 WRN] No tags found for api 'contacts;rev=1' and operation upsert-dataverse-contact
[23:09:04 INF] contacts;rev=1 API data found ...
[23:09:05 WRN] No diagnostics found for api redacted-api2;rev=1
[23:09:05 INF] redacted-api2;rev=1 Product API found ...
[23:09:05 INF] Extracting products from redacted-api2;rev=1 API:
[23:09:05 WRN] No tags found for api redacted-api2;rev=1
[23:09:05 WRN] No tags found for api 'redacted-api2;rev=1' and operation get-assets
[23:09:05 WRN] No tags found for api 'redacted-api2;rev=1' and operation get-assets-warranty
[23:09:05 INF] redacted-api2;rev=1 API data found ...
[23:09:05 WRN] No diagnostics found for api devices;rev=1
[23:09:05 WRN] Policy for api devices;rev=1 not found
[23:09:06 INF] devices;rev=1 Product API found ...
[23:09:06 INF] Extracting products from devices;rev=1 API:
[23:09:06 WRN] No tags found for api devices;rev=1
[23:09:06 WRN] No tags found for api 'devices;rev=1' and operation get-device
[23:09:06 WRN] No tags found for api 'devices;rev=1' and operation get-devices
[23:09:06 WRN] No tags found for api 'devices;rev=1' and operation sync-devices
[23:09:06 INF] devices;rev=1 API data found ...
[23:09:06 WRN] No diagnostics found for api redacted-api;rev=1
[23:09:07 INF] redacted-api;rev=1 Product API found ...
[23:09:07 INF] Extracting products from redacted-api;rev=1 API:
[23:09:07 WRN] No tags found for api redacted-api;rev=1
[23:09:07 WRN] No tags found for api 'redacted-api;rev=1' and operation create-order
```

### Anything else?

The only recent change I've made was to add some operations to existing APIs.

I've been using Reskit v1.0.0 this whole time, and extractor was working last Thursday.

**Comment by sh-jthorpe** [comment]
Just noticed i missed the most important part of the logs:

```
[12:47:49 INF] Started generation of groups template...
[12:47:51 ERR] Error occured: Response status code does not indicate success: 400 (Bad Request).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.CallApiManagementAsync(String azToken, String requestUrl, Boolean useCache, ClientHttpMethod method) in D:\a\_work\1\s\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 61
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.<>c__DisplayClass13_0`1.<<GetPagedResponseAsync>g__MakePagedRequestAsync|0>d.MoveNext() in D:\a\_work\1\s\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 86
--- End of stack trace from previous location ---
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.GetPagedResponseAsync[TResponse](String azToken, String requestUrl) in D:\a\_work\1\s\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 0
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Groups.GroupsClient.GetAllAsync(ExtractorParameters extractorParameters) in D:\a\_work\1\s\src\ArmTemplates\Common\API\Clients\Groups\GroupsClient.cs:line 38
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.GroupExtractor.GenerateGroupsTemplateAsync(ExtractorParameters extractorParameters) in D:\a\_work\1\s\src\ArmTemplates\Extractor\EntityExtractors\GroupExtractor.cs:line 43
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateGroupsTemplateAsync(String baseFilesGenerationDirectory) in D:\a\_work\1\s\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 298
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateTemplates(String baseFilesGenerationDirectory, String singleApiName, List`1 multipleApiNames, Template`1 apiTemplate) in D:\a\_work\1\s\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 1171
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.ExecuteGenerationBasedOnConfiguration() in D:\a\_work\1\s\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 235
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommandAsync(ExtractorParameters parameters) in D:\a\_work\1\s\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 68
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.CallApiManagementAsync(String azToken, String requestUrl, Boolean useCache, ClientHttpMethod method) in D:\a\_work\1\s\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 61
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.<>c__DisplayClass13_0`1.<<GetPagedResponseAsync>g__MakePagedRequestAsync|0>d.MoveNext() in D:\a\_work\1\s\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 86
--- End of stack trace from previous location ---
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.GetPagedResponseAsync[TResponse](String azToken, String requestUrl) in D:\a\_work\1\s\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 0
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Groups.GroupsClient.GetAllAsync(ExtractorParameters extractorParameters) in D:\a\_work\1\s\src\ArmTemplates\Common\API\Clients\Groups\GroupsClient.cs:line 38
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.GroupExtractor.GenerateGroupsTemplateAsync(ExtractorParameters extractorParameters) in D:\a\_work\1\s\src\ArmTemplates\Extractor\EntityExtractors\GroupExtractor.cs:line 43
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateGroupsTemplateAsync(String baseFilesGenerationDirectory) in D:\a\_work\1\s\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 298
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateTemplates(String baseFilesGenerationDirectory, String singleApiName, List`1 multipleApiNames, Template`1 apiTemplate) in D:\a\_work\1\s\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 1171
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.ExecuteGenerationBasedOnConfiguration() in D:\a\_work\1\s\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 235
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommandAsync(ExtractorParameters parameters) in D:\a\_work\1\s\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 68
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext() in D:\a\_work\1\s\src\ArmTemplates\Program.cs:line 45
--- End of stack trace from previous location ---
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.Main(String[] args) in D:\a\_work\1\s\src\ArmTemplates\Program.cs:line 38
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.<Main>(String[] args)
```

**Comment by benblokcegeka** [comment]
As extra info, the content of the 400 response is:

```
{
    "error": {
        "code": "MethodNotAllowedInPricingTier",
        "message": "Method not allowed in Consumption pricing tier",
        "details": null
    }
}
```

Which is kind of weird and seems to be a recent change as I did export product templates at least up till the 9th of December (12 days ago)

**Comment by tomkerkhove** [comment]
Product export is not the same as group export though because Products are supported in Consumption tier but groups are not.

You can learn more in our [feature](https://learn.microsoft.com/en-us/azure/api-management/api-management-features) and  [gateway overview](https://learn.microsoft.com/en-us/azure/api-management/api-management-gateways-overview).

**Comment by sh-jthorpe** [comment]
Just to clarify, I am not trying to export groups, because as you rightly pointed out, they're not supported on the Consumption tier.

So I believe this is a bug, because I have not configured Extractor to extract Groups, but it's still trying to.

**Comment by tomkerkhove** [comment]
Ok so the bug is in the extractor then

**Comment by sh-jthorpe** [comment]
Hi @f-alizada, thanks for working on this. I just wanted to ask if this is being worked on, or if you're planning to work on it?

**Comment by f-alizada** [comment]
@sh-jthorpe Hello. 
Sorry for the late response. Yes, it is planned to work on, and the PR will be attached to the issue. 
Unfortunately, first approach was not efficient and PR was closed. 
Best regards

**Comment by f-alizada** [comment]
Hello @sh-jthorpe.
The PR fixing the issue now is merged into the main branch. 
I would like to mention that the project is now in "maintenance" mode: 
https://github.com/Azure/azure-api-management-devops-resource-kit#azure-api-management-devops-resource-kit
