### ISSUE TITLE
Bug: Extractor Tool fails with 404

### ISSUE THREAD

**Issue by rsch136** [Azure/azure-api-management-devops-resource-kit#850]
### Report

Running the extractor tool fails with the following error message: "Error occured[sic]: Response status code does not indicate success: 404 (Not Found)."

I have verified the following (based on older issue [564](https://github.com/Azure/azure-api-management-devops-resource-kit/issues/564)):

- `az login`
- `az account set --subscription <subscription_id>`
- resource group is in `az group list`
- names of the source and destination APIM are correct
- serviceBaseUrl is set to `https://management.azure.com`

### Expected Behavior

I expect the exporter tool to export a set of json files, some folders and a yaml that I can then use with the creator tool to create the API in the QA instance of APIM.

### Actual Behavior

The exporter tool fails with the error message: "Error occured[sic]: Response status code does not indicate success: 404 (Not Found)."

### Steps to Reproduce the Problem

1. `az login` -> works
2. `az account set --subscription <subscription_id>` -> subscription is set to subscription of source apim
3. `az group list` -> rg is in list
4. `cd .\src\ArmTemplates`
5. `dotnet run extract --extractorConfig "C:\Users\*****\APIM\extractorConfig.json"` fails

### Component

Extractor

### DevOps Resource Kit Version

1.0.0 including commit f87976898

### .NET Version

6.0.404

### OS

Windows 11

### Configuration

Configuration:

```json
{
    "sourceApimName": "*****-apim-dev",
    "destinationApimName": "*****-apim-qa",
    "resourceGroup": "rg-apim-dev",
    "fileFolder": "c:\\Users\\*****\\APIM\\APIM_Extracts\\Test_API\\",
    "apiName": "Test API",
    "serviceBaseUrl": "https://management.azure.com"
}
```

### API Management Configuration

I have full admin rights to both APIM services, the resource groups, and subscriptions. The service is in a VNET.

### Logs

```shell
PS C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates> dotnet run
extract --extractorConfig "c:\Users\*****\APIM\extractorConfig.json"
[12:41:52 INF] Booting up Azure-Api-Management-DevOps-Resource-Kit v0.0.0.0 running .NET .NET 6.0.12
[12:41:52 INF] Recognized extract command...
[12:41:52 INF] API Management Template
[12:41:52 INF] Connecting to *****-apim-dev API Management Service on rg-apim-dev Resource Group ...
[12:41:52 INF] No specific parameters are set for template generation...
[12:41:52 INF] Started generation of api template...
[12:42:01 ERR] Error occured: Response status code does not indicate success: 404 (Not Found).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.CallApiManagementAsyn
c(String azToken, String requestUrl, Boolean useCache, ClientHttpMethod method) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 52
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.<>c__DisplayClass13_0
`1.<<GetPagedResponseAsync>g__MakePagedRequestAsync|0>d.MoveNext() in C:\Users\*****\repos\azu
re-api-management-devops-resource-kit\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 84
--- End of stack trace from previous location ---
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.GetPagedResponseAsync
[TResponse](String azToken, String requestUrl) in C:\Users\*****\repos\azure-api-management-de
vops-resource-kit\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 71
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.ApiSchemas.ApiSchemaClient.GetApiSchemasAsync(St
ring apiName, ExtractorParameters extractorParameters) in C:\Users\*****\repos\azure-api-manag
ement-devops-resource-kit\src\ArmTemplates\Common\API\Clients\ApiSchemas\ApiSchemaClient.cs:line 35
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.ApiSchemaExtractor.GenerateApiSchemaReso
urcesAsync(String apiName, ExtractorParameters extractorParameters) in C:\Users\*****\repos\az
ure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\ApiSchemaExtractor.cs:line 33
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.ApiExtractor.GetApiRelatedTemplateResour
cesAsync(String apiName, String baseFilesGenerationDirectory, ExtractorParameters extractorParameters) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\APIExtrac
tor.cs:line 191
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.ApiExtractor.GenerateSingleApiTemplateRe
sourcesAsync(String singleApiName, String baseFilesGenerationDirectory, ExtractorParameters extractorParameters, String apiDepe
nds) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extract
or\EntityExtractors\APIExtractor.cs:line 102
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.ApiExtractor.GenerateApiTemplateAsync(St
ring singleApiName, List`1 multipleApiNames, String baseFilesGenerationDirectory, ExtractorParameters extractorParameters) in C
:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\Entity
Extractors\APIExtractor.cs:line 76
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateApiTemplateAsync(Strin
g singleApiName, List`1 multipleApiNames, String baseFilesGenerationDirectory) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 410
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateTemplates(String baseF
ilesGenerationDirectory, String singleApiName, List`1 multipleApiNames, Template`1 apiTemplate) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:lin
e 1159
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.ExecuteGenerationBasedOnConfig
uration() in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Co
mmands\Executors\ExtractorExecutor.cs:line 235
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommandAsync
(ExtractorParameters parameters) in C:\Users\*****\repos\azure-api-management-devops-resource-
kit\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 68
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.CallApiManagementAsyn
c(String azToken, String requestUrl, Boolean useCache, ClientHttpMethod method) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 52
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.<>c__DisplayClass13_0
`1.<<GetPagedResponseAsync>g__MakePagedRequestAsync|0>d.MoveNext() in C:\Users\*****\repos\azu
re-api-management-devops-resource-kit\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 84
--- End of stack trace from previous location ---
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.Abstractions.ApiClientBase.GetPagedResponseAsync
[TResponse](String azToken, String requestUrl) in C:\Users\*****\repos\azure-api-management-de
vops-resource-kit\src\ArmTemplates\Common\API\Clients\Abstractions\ApiClientBase.cs:line 71
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Common.API.Clients.ApiSchemas.ApiSchemaClient.GetApiSchemasAsync(St
ring apiName, ExtractorParameters extractorParameters) in C:\Users\*****\repos\azure-api-manag
ement-devops-resource-kit\src\ArmTemplates\Common\API\Clients\ApiSchemas\ApiSchemaClient.cs:line 35
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.ApiSchemaExtractor.GenerateApiSchemaReso
urcesAsync(String apiName, ExtractorParameters extractorParameters) in C:\Users\*****\repos\az
ure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\ApiSchemaExtractor.cs:line 33
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.ApiExtractor.GetApiRelatedTemplateResour
cesAsync(String apiName, String baseFilesGenerationDirectory, ExtractorParameters extractorParameters) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\EntityExtractors\APIExtrac
tor.cs:line 191
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.ApiExtractor.GenerateSingleApiTemplateRe
sourcesAsync(String singleApiName, String baseFilesGenerationDirectory, ExtractorParameters extractorParameters, String apiDepe
nds) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extract
or\EntityExtractors\APIExtractor.cs:line 102
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Extractor.EntityExtractors.ApiExtractor.GenerateApiTemplateAsync(St
ring singleApiName, List`1 multipleApiNames, String baseFilesGenerationDirectory, ExtractorParameters extractorParameters) in C
:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Extractor\Entity
Extractors\APIExtractor.cs:line 76
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateApiTemplateAsync(Strin
g singleApiName, List`1 multipleApiNames, String baseFilesGenerationDirectory) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:line 410
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.GenerateTemplates(String baseF
ilesGenerationDirectory, String singleApiName, List`1 multipleApiNames, Template`1 apiTemplate) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Commands\Executors\ExtractorExecutor.cs:lin
e 1159
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Executors.ExtractorExecutor.ExecuteGenerationBasedOnConfig
uration() in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Co
mmands\Executors\ExtractorExecutor.cs:line 235
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Commands.Applications.ExtractApplicationCommand.ExecuteCommandAsync
(ExtractorParameters parameters) in C:\Users\*****\repos\azure-api-management-devops-resource-
kit\src\ArmTemplates\Commands\Applications\ExtractApplicationCommand.cs:line 68
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext() in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Program.cs:line 45
--- End of stack trace from previous location ---
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.Main(String[] args) in C:\Users\*****\repos\azure-api-management-devops-resource-kit\src\ArmTemplates\Program.cs:line 38
   at Microsoft.Azure.Management.ApiManagement.ArmTemplates.Program.<Main>(String[] args)
```

**Comment by rsch136** [comment]
I have found a workaround. Using the api management extension for vsc I can "extract" the API that I want. This will create a json that the extractor doesn't fail with. Not sure why however.

**Comment by f-alizada** [comment]
Hello @rsch136, thank you for raising the issue. 
From the provided config: 
```
{
    "sourceApimName": "*****-apim-dev",
    "destinationApimName": "*****-apim-qa",
    "resourceGroup": "rg-apim-dev",
    "fileFolder": "c:\\Users\\*****\\APIM\\APIM_Extracts\\Test_API\\",
    "apiName": "Test API",
    "serviceBaseUrl": "https://management.azure.com"
}
```
it seems that for apiName field display name was used, it is supposed to be name of the api (could be found in settings page of api). 
For paramNamedValue I suggest to create separate issue if this is still the case. 
Best regards.
Thank you for feedback!

**Comment by rsch136** [comment]
Thanks!
I missed that.

**Comment by bacpac** [comment]
We accidentally removed an old API but forgot to change the extractor params, this topic helped us solve the issue, thanks.

It would be nice though if the logs with the 404 would mention what data exactly it's trying to retrieve. That would make debugging a lot easier :)
